### ISSUE TITLE
Logbook will change response header  during pure servlet project

### ISSUE THREAD

**Issue by wyzssw** [zalando/logbook#1199]
LogbookFilter flush buffer will make  tomcat add `Transfer-Encoding: chunked` header

## Description
In pure servlet project , no spring mvc , no spring boot
`LogbookFilter`
```

  private void write(RemoteRequest request, LocalResponse response, ResponseWritingStage writing) throws IOException {
        final AtomicBoolean attribute = (AtomicBoolean) request.getAttribute(responseWritingStageSynchronizationName);
        if (!attribute.getAndSet(true)) {
            response.flushBuffer(); // <---- will triger tomcat  org.apache.coyote.http11.AbstractHttp11Processor#prepareResponse which will add header Transfer-Encoding: chunked but not content-length
            writing.write();
        }
    }

```

## Expected Behavior
```
curl -i 'http://127.0.0.1:8089/servlettest/helloworld'
HTTP/1.1 200
Content-Length: 10
Date: Thu, 21 Oct 2021 08:29:25 GMT

helloworld
```

## Actual Behavior

```
curl -i 'http://127.0.0.1:8089/servlettest/helloworld'
HTTP/1.1 200
Transfer-Encoding: chunked
Date: Thu, 21 Oct 2021 08:38:23 GMT

helloworld
```
It is compatible to  use standard http client ，but there will be problems when use raw http parser which only support content-length 
 
## Possible Fix
Refer to Springboot
`org.springframework.http.converter.AbstractHttpMessageConverter#addDefaultHeaders`
add default headers include `Content-Length`

## Steps to Reproduce

1.  create a pure servlet project
2. import logbook dependency, add logbookfilter to web.xml 
3. add a servlet class
```
public class HelloworldServlet extends HttpServlet {

    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws IOException {
        resp.getWriter().write("helloworld");
    }
}
```
4. mvn clean package to project.war ,add copy to tomcat/webapps/
5. bin/catalina.sh start 

## Context
My team has a old  pure servlet project , which not depend on springmvc。Some raw c++ http client cannot recognize the `Transfer-Encoding` header ，can not parse response body without `Content-Length`

## Your Environment

* Version used: Logbook 2.14.0 ,  Tomcat 8.0
* Link to your project: not upload

**Comment by nhmarujo** [comment]
Hi. Can this be given some priority? Since the fixes introduced in https://github.com/zalando/logbook/pull/1201, this wrong behaviour on a server causes, under certain circumstances, issues when used in combination with `LogbookExchangeFilterFunction` on the client side.
The circumstances on which the issue occurs is when we have a controller with an endpoint with `void` return type. The response will return `Transfer-Encoding: chunked`, although there is no content.
On the client side this will result on `LogbookExchangeFilterFunction` entering [this if](https://github.com/zalando/logbook/blob/a382925726becf0e591e90e1fe12cdd79fc106b2/logbook-spring-webflux/src/main/java/org/zalando/logbook/spring/webflux/LogbookExchangeFilterFunction.java#L45), which will then cause it to blow with the following stacktrace:
```java
java.lang.IllegalStateException: The underlying HTTP client completed without emitting a response.
	at org.springframework.web.reactive.function.client.DefaultWebClient.lambda$static$0(DefaultWebClient.java:73)
	at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4490)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onComplete(FluxOnAssembly.java:549)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onComplete(FluxContextWrite.java:126)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:128)
	at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onComplete(FluxDoOnEach.java:223)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:196)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onComplete(MonoFlatMap.java:268)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:277)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onComplete(ScopePassingSpanSubscriber.java:103)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:152)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:277)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onComplete(FluxOnAssembly.java:549)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:152)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onComplete(FluxContextWrite.java:126)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onComplete(FluxMapFuseable.java:350)
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onComplete(FluxFilterFuseable.java:391)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1840)
	at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:160)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onComplete(ScopePassingSpanSubscriber.java:103)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onComplete(ScopePassingSpanSubscriber.java:103)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:415)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:424)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:478)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:712)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by nhmarujo** [comment]
@kasmarian @kumarprabhashanand @lukasniemeier-zalando @msdousti can we get some attention on this one? Sorry if I tagged anyone incorrectly - I tried to tag the people I assume are the official maintainers from Zalando now (judging by commit history and profile description).

**Comment by kasmarian** [comment]
Hi @nhmarujo, the fix for webflux should be available with the next release, see PR - https://github.com/zalando/logbook/pull/1476. As for the original issue, I don't have a good idea in mind how to address it. If someone has an approach in mind, please share your thoughts or suggest the change via pull request.

**Comment by nhmarujo** [comment]
Hi @kasmarian . Thank you so much! I checked the fix and it looks perfect.

**Comment by kasmarian** [comment]
Closing the issues as it's fixed in https://github.com/zalando/logbook/pull/1476

**Comment by dartilla** [comment]
Guys, why do closed this issue?
As I see fix is for webflux only, however this issue is for Tomcat and still reproducable.

**Comment by dartilla** [comment]
Is there any reason to do `response.flushBuffer()` except broken `AsyncDispatchTest.shouldFormatAsyncServletResponseGet` and `TeeTest.shouldSupportReader`?
Making implementation of `HttpFilter` intentionally flush response buffer seems really strange to me.
And yes, it brakes `Transfer-Encoding` and `Content-Type` in tomcat in case empty response body.

**Comment by kasmarian** [comment]
@dartilla  Ah you're right, the initial issue was not resolved, only the reactive stack one was. Let's re-open it. 

As per `response.flushBuffer()`, my understanding is that without this step, the response body may not yet be available for logging yet. If you have suggestions how to overcome this, please share or feel free to open a pull request with a proposal.
